version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app

  db:
    container_name: hello-go-db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root